name: DataParser

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            uses: actions/checkout@v2
            name: Install-Qt
                uses: jurplel/install-qt-action@v2
            name: create-build-dir
                run: mkdir build
            name: build-qmake
                working-directory: ./build
                run: qmake -o Makefile ..
            name: build-make
                working-directory: ./build
                run: make
            name: run-test
                working-directory: ./build
                run: ./ParserTest/ParserTest
            name: zip-app
                run: zip -r dataviewer.zip build/DataViewer/DataViewer
            name: deploy-app
                uses: appleboy/scp-action@master
                with:
                    host: *
                    username: *
                    password: *
                    port: 22
                    source: *
                    target: *